services:
  - type: web
    name: garilink-backend-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.orlrgjjbmnjxqbhheago:Kibaja0658%23@aws-0-eu-west-1.pooler.supabase.com:5432/postgres?pgbouncer=true
      - key: JWT_ACCESS_SECRET
        value: garilink_access_secret_key_minimum_32_chars_secure
      - key: JWT_REFRESH_SECRET
        value: garilink_refresh_secret_key_minimum_32_chars_secure
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
