begin;
-- Normalize absent historical snapshot keys only for retry comparison.
create or replace function public.garilink_create_rental(input jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=garilink_private.require_user(); r_item record; v_listing public.gl_listings; v_old public.gl_rentals; v_created public.gl_rentals; v_request uuid; v_start date; v_end date; v_notes text; v_need jsonb; v_canonical jsonb;
begin
 if input is null or jsonb_typeof(input)<>'object' then raise exception 'Invalid rental request' using errcode='22023'; end if;
 for r_item in select item.key,item.value from jsonb_each(input) as item loop if r_item.key not in ('listingId','requestId','startDate','endDate','pickupNotes','transportNeed') or (r_item.key<>'transportNeed' and jsonb_typeof(r_item.value)<>'string') then raise exception 'Invalid rental field' using errcode='22023'; end if; end loop;
 begin v_request:=(input->>'requestId')::uuid;v_start:=(input->>'startDate')::timestamptz::date;v_end:=(input->>'endDate')::timestamptz::date; exception when others then raise exception 'Invalid rental dates or request ID' using errcode='22023'; end;
 v_notes:=nullif(trim(input->>'pickupNotes'),'');v_need:=case when input ? 'transportNeed' then garilink_private.validate_transport_need(input->'transportNeed') else null end;
 if v_start<=current_date or v_end<=v_start or v_end>v_start+366 or char_length(v_notes)>1000 then raise exception 'Invalid rental dates or notes' using errcode='22023'; end if;
 select l.* into v_listing from public.gl_listings l where l.id=(input->>'listingId')::uuid for share; if not found or v_listing.type<>'FOR_HIRE' or not garilink_private.listing_visible(v_listing) then raise exception 'Listing not found' using errcode='PT404'; end if; if exists(select 1 from public.gl_workspaces w where w.id=v_listing.workspace_id and (w.owner_id=v_actor or exists(select 1 from public.gl_workspace_members m where m.workspace_id=w.id and m.user_id=v_actor and m.status='ACTIVE'))) then raise exception 'You cannot rent your own vehicle' using errcode='42501'; end if;
 v_canonical:=jsonb_build_object('listingId',v_listing.id,'startDate',v_start,'endDate',v_end,'pickupNotes',v_notes,'transportNeed',v_need); perform pg_advisory_xact_lock(hashtextextended(v_actor::text,2)); select r.* into v_old from public.gl_rentals r where r.customer_id=v_actor and r.request_id=v_request; if found then if (v_old.request_payload || jsonb_build_object('transportNeed',v_old.transport_need_snapshot))<>v_canonical then raise exception 'Request ID already used' using errcode='23505'; end if; return garilink_private.rental_json(v_old); end if;
 insert into public.gl_rentals(listing_id,vehicle_id,workspace_id,customer_id,request_id,request_payload,start_date,end_date,daily_rate,currency,total_amount,pickup_notes,transport_need_snapshot) values(v_listing.id,v_listing.vehicle_id,v_listing.workspace_id,v_actor,v_request,v_canonical,v_start,v_end,v_listing.price,v_listing.currency,v_listing.price*(v_end-v_start),v_notes,v_need) returning * into v_created; return garilink_private.rental_json(v_created);
end; $$;
commit;
